### ISSUE TITLE
More versatile search

### ISSUE THREAD

**Issue by svekko** [Tomburgs/agloe#3]
I think that the order of words in a search value shouldn't matter. For `Friends Cafe`, I'd expect to find it when I enter `cafe friends` or for `Chez Olivier Cafe`, I'd expected to find it when entering `cafe olivier`, `cafe chez` or `chez cafe`.

**Comment by Tomburgs** [comment]
I had a similar idea which consisted of implementing fuzzy search, however, fuzzy searches are going to return a lot more results and they should be ranked, which would ask us to re-organize the results multiple times during the stream which could lead to a worse UX.

I think your idea of just ignoring the word order could work very well. If you're interested in picking this up let me know, [this](https://github.com/Tomburgs/agloe/blob/master/src/go/parser/parser.go#L23,L28) is where the matching happens and [here](https://github.com/Tomburgs/agloe/blob/master/src/go/main.go#L34) the search term gets parsed.

**Comment by Tomburgs** [comment]
Fuzzy search implemented in #4.
